### ISSUE TITLE
Per scene breakdown of quantitative results for DyNeRF dataset

### ISSUE THREAD

**Issue by JokerYan** [zju3dv/im4d#2]
Hi,

Thanks for the great work. May I ask whether there is a per-scene breakdown of the quantitative results for the DyNeRF dataset. The paper says it will be included in the supplementary, but I can't seem to find it? May I ask whether the result for the DyNeRF dataset is calculated on the flame_salmon scene or all the scenes together?

Thanks!

**Comment by haotongl** [comment]
Hi, thank you for your attention! 
The result for the DyNeRF dataset is calculated on the first 300 frames of cut_beef scene. (We does not include the per-scene breakdown for the DyNeRF dataset as only one scene is used for evaluation.)

The code for our proposed evaluation setting on the dynerf dataset (dynamic region definitions) can be found in:
https://github.com/zju3dv/im4d/blob/main/scripts/preprocess/dynerf/gen_diff_patch.py#L105

**Comment by JokerYan** [comment]
Thank you for the fast response! This is very helpful. I am really a big fan of you from ENeRF. Great work!
