### ISSUE TITLE
Dataset Transform to Align Camera Extrinsics

### ISSUE THREAD

**Issue by ZhaoLizz** [zju3dv/im4d#3]
Hi! 
Thanks for the great work.
I've noticed that the  `base_dataset.py` seems to expect a 4x4 transform matrix from the `dataset_cfg` to align the camera extrinsic Z-axis to the up direction. [base_dataset.py](https://github.com/zju3dv/im4d/blob/main/lib/datasets/volcap/base_dataset.py#L78C94-L78C94)

I've attempted to visualize this transform and apply it to the camera extrinsics using the following code:

```python
import open3d as o3d # 0.16.0
import numpy as np

if __name__ == "__main__":

    # Step 0 - Init
    WIDTH = 1280
    HEIGHT = 720

    # Step 1 - Get scene objects
    meshFrame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=2.0, origin=[0, 0, 0])
    
    # Step 2 - Create visualizer object
    vizualizer = o3d.visualization.Visualizer()
    vizualizer.create_window()
    vizualizer.create_window(width=WIDTH, height=HEIGHT)

    # Step 3 - Add objects to visualizer
    vizualizer.add_geometry(meshFrame)
    
    # NHR Baskball Dataset Camera Params
    dataset_trans = np.array([[ 0.90630779 ,-0.07338689,  0.41619774 , 2.        ],
 [ 0.42261826  ,0.1573787,  -0.89253894, -5.13      ],
 [ 0.         , 0.98480775 , 0.17364818 , 2.85      ],
 [ 0.          ,0.        ,  0.        ,  1.        ]])
    intrinsic = np.array([[ 2.3717e+03, -1.0060e+00,  5.2414e+02],
        [ 0.0000e+00,  2.3718e+03,  4.1167e+02],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00]])
    Rt = np.array([[-0.6087, -0.2077,  0.7657,  3.3700],
        [ 0.0279, -0.9701, -0.2410, -2.1150],
        [ 0.7929, -0.1253,  0.5963,  6.6570],
        [ 0.0000,  0.0000,  0.0000,  1.0000]]) # extrinsic, world2cam
    
    # Rt = Rt @ np.linalg.inv(dataset_trans) # whether to transform the camera extrinsic
    cam2world = np.linalg.inv(Rt)
    camFrame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1.0)
    camFrame.transform(cam2world)
    vizualizer.add_geometry(camFrame)

    # Visulize camera
    camera_in = o3d.camera.PinholeCameraIntrinsic()
    camera_in.intrinsic_matrix = intrinsic
    camera = o3d.camera.PinholeCameraParameters()
    camera.intrinsic = camera_in
    camera.extrinsic = Rt
    cameraLines = o3d.geometry.LineSet.create_camera_visualization(intrinsic=camera.intrinsic, extrinsic=camera.extrinsic)
    vizualizer.add_geometry(cameraLines)
    vizualizer.run()
    
```
However, my results seem to indicate that this operation is primarily rotating the camera coordinate system along the Z-axis, as in the following figure:
![tranvis](https://github.com/zju3dv/im4d/assets/29300861/6195bc3f-2323-4108-a56b-0eb50b479c67)

I would greatly appreciate your help in clarifying the usage of the dataset transform. Specifically, I'm interested in understanding the following:

* What is the intended purpose of the dataset_cfg transform in aligning the camera extrinsic Z-axis to the up direction?
* How should I create this transform for my custom dataset? Are there specific guidelines or steps to follow?

Thanks in advance!

**Comment by haotongl** [comment]
Hi, the transform is taking from:
https://github.com/zju3dv/mlp_maps/blob/master/configs/nhr/sport1.py#L133

One advantage of aligning the camera extrinsic to one axis is that it can make the bounding box wrap around the human body more tightly, allowing for more efficient use of grid planes.

For ordinary data, I believe it can be manually adjusted through MeshLab. EasyMocap also provides some automated annotation tools, such as using a checkerboard, assuming it is placed horizontally on the ground, to calibrate the camera and align the world system with the checkerboard.

**Comment by ZhaoLizz** [comment]
Thanks for the advice.
