### ISSUE TITLE
AssertionError: /data/renbody/0013_09/intri.yml

### ISSUE THREAD

**Issue by anidealeft** [zju3dv/im4d#4]
hello, it's a really nice work!  but some error occurs to me when I try to do testing(Reproduce the quantitative results in the paper.） what I input is  [python run.py --type evaluate --cfg_file configs/exps/im4d/renbody/0013_09.yaml save_result True] , but it shows two strange error :
1.[pretrained model does not exist: /data/trained_model/0013_09/im4d/0013_09]
2.AssertionError: /data/renbody/0013_09/intri.yml
but I check the path I set is just right , could you please give me any advice?
![4e911614836ded353e5a89ed7c8c962](https://github.com/zju3dv/im4d/assets/77136576/9858281f-f4a2-4d71-9d5a-075aba162be8)
![d684f840341f1fa5a896640f7e761d4](https://github.com/zju3dv/im4d/assets/77136576/afef1ded-3e51-4b10-ad90-1292ee98f48c)
![7dc712f0251115136d140a5a0e1e00f](https://github.com/zju3dv/im4d/assets/77136576/544930eb-4dde-4507-a566-6491e3386f1a)
![ea7da6fe579ef8f6602e45b74a983ef](https://github.com/zju3dv/im4d/assets/77136576/b2479ac0-c900-44f9-9c22-412538de2b54)

**Comment by haotongl** [comment]
It seems that your workspace is set incorrectly. Maybe you should execute the following command:
`export workspace=/data/im4d-main/data`
