### ISSUE TITLE
No file renbody\0013_01\ intr.yml

### ISSUE THREAD

**Issue by swpucwf** [zju3dv/im4d#6]
python run.py --type evaluate --cfg_file configs/exps/im4d/renbody/0013_01.yaml save_result True After running the command, I am prompted that there is no file renbody\0013_01\ intr.yml, I would like to ask if this file is missing

**Comment by haotongl** [comment]
Thanks for your attention! Do you use the data processed by us? 
Please refer to this [issue](https://github.com/zju3dv/im4d/issues/5)  for the processed data.
