### ISSUE TITLE
How to prepare the DNA-Rendering dataset?

### ISSUE THREAD

**Issue by Winter-Dry** [zju3dv/im4d#9]
Thanks for your wonderful work!

I am trying trying to training with theDNA_Rendering data, but we lack of the .ply file in pointcloud_denoise folder, could you please tell us how to get these point cloud files?

Thanks again, looking forward for your reply!!!

**Comment by haotongl** [comment]
Hi, we have updated the tutorial. https://github.com/zju3dv/im4d/blob/main/docs/custom_data_tutorial.md
